project:
  type: website
  output-dir: docs
  
website:
  title: "BEHDS"
  navbar:
    left:
      - text: Home
        href: index.qmd
      - text: "bids"
        href: bids.qmd
      - text: "Get started:"
        menu:
           - text: Software Requirements
             href: requirements.qmd
           - text: Set up
             href: behds.qmd
           - text: Example Workflow
             href: Example.qmd
    tools:
      - icon: github
        href: https://github.com/FloPaho/building-resilience
  page-footer:
    right: "Built with [Quarto](https://quarto.org/)"

format:
  html:
    theme: Journal
    toc: true

editor: source

