---
title: "BIDS Format and Validation"
format:
  html:
    toc: true
---


Upon downloading BEHDS.R, you will first need to extract the data. After extraction, you should have the following folder structure:

- BEHDS 0.3.5/
  - code/
  - projectdata/
  - rawdata/
  - resources/
  - templates/
  - behds.R

## 1: Project Data

1. Create a new folder named after your project within the `projectdata/` directory.
2. **Copy** `template.xlsx` from the `templates/` folder to your project folder. Rename this file to `YourProjectName.xlsx` and fill in the required information. This file should contain all variables related to **demographic data and variables not collected via questionnaires**. Ensure that the names used in the "ItemName" column correspond with those used in the raw data columns.
3. **Copy** `template_info.xlsx` from the `templates/` folder to your project folder. Rename this file to `YourProjectName_info.xlsx` and complete the required information.

## 2: Raw Data

1. Create a new folder named after your project within the `rawdata/` directory.

### 2.1: Adjusting Raw Data

Depending on how your data was gathered, it might need to be restructured to meet the program's requirements. Modify your data using a spreadsheet application such as Excel. 

- Save this modified file in the newly created project folder as `YourProjectName_raw.xlsx`. The specific name of the raw data files does not matter.

### 2.2: Structuring `YourProjectName_raw.xlsx` and Similar Files

**First Column**
- Name the first column "id".
- This column must contain the participant ID (e.g., participant code or sequential number).
- Data will be merged based on this ID, so it must be consistent across all files. Ensure it is always the same for each participant to avoid input errors.

**Second Column**
- Name the second column "ses".
- This column must indicate the session/measurement time point (e.g., 1, 2, 3 or pre, post).
- If there is only one measurement time point, enter "1". The program will not function otherwise. Data for each measurement time point must be in a separate row.

**Ensure Correct Order and Naming of Questionnaire Items**
- The subsequent columns should be named and filled according to all the items provided in the project data step.
- The columns for questionnaire items must be in the correct order.
- Column names must include the name of the questionnaire and must not be immediately preceded or followed by a letter.
  - Example for the questionnaire "TEST":
    - Correct: `TEST-01`, `TEST01`, `TEST_01`, `[TEST01]`, `TEST[TEST01]`
    - Incorrect: `QTEST01`, `TESTshort01`, `kTEST01`, `test01`

**You can create multiple files containing all your data; it does not all have to be in one file. Ensure the "id" and "ses" columns are correct in each file.**

## 3: Resources

### 3.1: Creating a Questionnaire
- If the required questionnaire is not present in the `resources` folder:
  - Create it using the `questionnairetemplate.xlsx` file from the `templates` folder.
  - Save the newly created questionnaire in the `resources` folder with the test name as the file name (e.g., for the "TEST" questionnaire: `TEST.xlsx`).

### 3.2: Modifying a Questionnaire
- If a modified version of a questionnaire from the `resources` folder is used for this project:
  - Adjust the file as needed.
  - Save the modified file in the project folder under `projectdata` with the same name.
    - For example, the program will prefer `TEST.xlsx` in the project folder `projectdata` over `TEST.xlsx` in the `resources` folder.

## 4: Finished Data Structure

The finished data structure should look as follows:

- projectdata
  - YourProjectName
    - YourProjectName.xlsx
    - YourProjectName_info.xlsx
    - TEST.xlsx (Modified version of the TEST questionnaire, optional)
- rawdata
  - YourProjectName
    - Rawdatafile1.xlsx
    - Rawdatafile2.xlsx
    - Rawdatafile3.xlsx
    - ...
- resources
  - Questionnaire1.xlsx
  - Questionnaire2.xlsx
  - Questionnaire3.xlsx
  
## How to Run BEHDS.R

1. Open `behds.R` in RStudio.
2. In the second line of code, enter your project name:
   - e.g., `proj = "YourProjectName"`
3. Press the `Source` button on the upper right side of the code window.
4. Wait for the process to finish; this could take some time.
5. You can find the converted BIDS structure in `bids/YourProjectName/rawdata`.
6. You can find the feedback file `YourProjectName.html` in `bids/YourProjectName/derivatives` as well as the finished `.csv` files. 